server:
  port: 8082

spring:
  application:
    name: categoria-service
  datasource:
    url: jdbc:mysql://localhost:3306/bd_categoria_dev?createDatabaseIfNotExist=true&serverTimezone=America/Lima
    username: root
    password:
